install.packages("tm")
y
install.packages("SnowballC")
install.packages("wordcloud")
install.packages("RColorBrewer")
library(NLP)
library(tm)
library(SnowballC)
library(RColorBrewer)
library(wordcloud)
myText = readLines('IfWeWereVillains.txt')
myCorpus <- Corpus(VectorSource(myText))
toSpace <- content_transformer(function(x , pattern) gsub(pattern, " ",x))
myCorpus <- tm_map(myCorpus, toSpace,"“")
myCorpus <- tm_map(myCorpus, toSpace,"”")
myCorpus <- tm_map(myCorpus, toSpace,"’")
myCorpus <- tm_map(myCorpus, content_transformer(tolower))
myCorpus <- tm_map(myCorpus, removeNumbers)
myCorpus <- tm_map(myCorpus, removeWords, stopwords("english"))
myCorpus <- tm_map(myCorpus, removeWords, "said")
myCorpus <- tm_map(myCorpus, removeWords, "i")
myCorpus <- tm_map(myCorpus, removeWords, "oliver")
myCorpus <- tm_map(myCorpus, removeWords, "james")
myCorpus <- tm_map(myCorpus, removeWords, "richard")
myCorpus <- tm_map(myCorpus, removeWords, "alexander")
myCorpus <- tm_map(myCorpus, removeWords, "filippa")
myCorpus <- tm_map(myCorpus, removeWords, "meredith")
myCorpus <- tm_map(myCorpus, removeWords, "wren")
myCorpus <- tm_map(myCorpus, removeWords, "frederick")
myCorpus <- tm_map(myCorpus, removeWords, "gwendolyn")
myCorpus <- tm_map(myCorpus, removeWords, "camilo")
myCorpus <- tm_map(myCorpus, removeWords, "shakespeare")
myCorpus <- tm_map(myCorpus, removeWords, "colborne")
myCorpus <- tm_map(myCorpus, removeWords, "s")
myCorpus <- tm_map(myCorpus, removeWords, "re")
myCorpus <- tm_map(myCorpus, removeWords, "nt")
myCorpus <- tm_map(myCorpus, removeWords, "don")
myCorpus <- tm_map(myCorpus, removePunctuation)
myCorpus <- tm_map(myCorpus, stripWhitespace)
dataMatrix <- TermDocumentMatrix(myCorpus)
myMatrix <- as.matrix(dataMatrix)
mySortedMatrix <- sort(rowSums(myMatrix),decreasing=TRUE)
wordDataFrame <- data.frame(word = names(mySortedMatrix),freq=mySortedMatrix)
head(wordDataFrame)
wordcloud(wordDataFrame$word,wordDataFrame$freq,min.freq=10,
colors=brewer.pal(10,"Paired"))
barplot(wordDataFrame[1:15,]$freq, las = 2, names.arg = wordDataFrame[1:15,]$word,
        col = "purple", main ="15 mots les plus fréquents",
        ylab = "Fréquence")
